# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8c2e9bc9e9b1e8a556baf0f962f5a1da37a3eac000bb2e7164e12b47b99aad7fb2f13f3cdbd3864380513e6715bdc5e383b93fb5aa8ea030be85e25f3c34c38

test:
  secret_key_base: a774997405c7d2a8cac0fc822398c5ff989d6ac52b05ddef346013f9bed6039598f2815e9528b236d6c301ddf7bdc8aa1a7e4aaeab266e19da56b13bd8ace494

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
